@startuml casodeuso

left to right direction
actor Cliente
actor Administrador
actor "Prestador de Serviços" as Prestador

rectangle CarXpress {

  Cliente -- (Efetuar reserva de veículo)
  Cliente -- (Cancelar reserva de veículo)
  Cliente -- (Efetuar pagamento)
  Cliente -- (Consultar histórico de reservas)
  Cliente -- (Consultar multas e contestá-las)
  Cliente -- (Consultar faturas)

  Administrador -- (Aprovar/rejeitar reservas)
  Administrador -- (Gerir pagamentos)
  Administrador -- (Gerir faturas)
  Administrador -- (Gerir multas e contestação)
  Administrador -- (Notificar cliente sobre multas)
  Administrador -- (Registar necessidade de manutenção)
  Administrador -- (Gerir estado do veículo)

  Prestador -- (Submeter orçamentos de manutenção)
  Prestador -- (Confirmar realização de manutenção)
}

(Efetuar pagamento) --> (Consultar faturas) : <<include>>
(Gerir pagamentos) --> (Gerir faturas) : <<include>>

@enduml