name: .NET Build and Publish Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies for API
      run: dotnet restore "RESTful API/RESTful API.csproj"

    - name: Restore dependencies for Unit Tests
      run: dotnet restore "Tests/CarXPress Unit Tests/CarXPress Unit Tests.csproj"

    - name: Restore dependencies for Integration Tests
      run: dotnet restore "Tests/CarXpressTesteIntegracao/CarXpressTesteIntegracao.csproj"

    - name: Build API
      run: dotnet build "RESTful API/RESTful API.csproj" --configuration Release --no-restore

    - name: Test Unit Tests
      run: dotnet test "Tests/CarXPress Unit Tests/CarXPress Unit Tests.csproj" --configuration Release --verbosity normal

    - name: Publish API
      run: dotnet publish "RESTful API/RESTful API.csproj" --configuration Release --no-build -o ./publish-output

    - name: Upload published artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-api-published
        path: backend/publish-output
